---
title: "P1805_hw5_jn2761"
author: "jiaying Ning"
date: "11/14/2020"
output: html_document
---


```{r setup, include=FALSE}
#loading package
library(tidyverse)
library(readxl)
library(janitor)
library(dplyr)
library(ggridges)


knitr::opts_chunk$set(
  fig.width = 6,
    fig.asp = .6,
  out.width = "90%"

)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete =scale_fill_viridis_d
```

```{r}
library(purrr)
```


## problem 2


```{r, error = TRUE}
df = 
  tibble(
    path = list.files("data"),
  ) %>% 
  mutate(
    path = str_c("data/", path),
    data = map(path,read.csv)) %>%
  unnest() %>% 
   mutate(path=gsub("data/","",path),
          path=gsub(".csv","",path)) %>%
   separate(path, c("control_arm","subject_id"), sep = "([_])") %>%
  relocate(subject_id,control_arm) %>%
   pivot_longer(
    week_1:week_8,
    names_to = "week", 
    names_prefix = "week_",
    values_to = "observation")


```


```{r}
df %>%
  filter(control_arm =="con") 
```
```{r}
df %>%
  group_by(subject_id)%>%
  ggplot(aes(x=week,y=observation,group=subject_id,color=subject_id))+
  geom_line() +
  stat_smooth(aes(group = 1),method = "lm", se = FALSE)+
  facet_grid(. ~ control_arm)
```
Overall, observation value seems to be higher as time pass by for the experimental group, and there seems to no correlation between time and observations for the control group.


## problem3

library
```{r}
library(broom)

```


```{r}
x=rnorm(n=30,mean=0,sd=5)

df=
tidy(t.test(rnorm(n=30,mean=0,sd=5))) %>%
  select(p.value) %>%
  mutate(x=list(rnorm(n=30,mean=0,sd=5)),
         mu=0,
         mean = mean(x[[1]]))%>%
 select(-x)




  

```

```{r}
tidy(t.test(rnorm(n=30,mean=0,sd=5))) %>%
  select(p.value) %>%
  mutate(x=list(rnorm(n=30,mean=0,sd=5)),
         mu=0,
         mean = mean(x[[1]]))%>%
 select(-x)
```




```{r}


sim_norm = function(size=30, mu, sigma = 5) {
  
  
tidy(t.test(rnorm(n=size, mean = mu, sd = sigma)),mu = 0,conf,leve=0.95,alternative="two.sided") %>%
  select(p.value) %>%
  mutate(x=list(rnorm(n=size, mean = mu, sd = sigma)),
         mean = mean(x[[1]]))%>%
 select(-x)
  
  
}



```




```{r}

mu_c =c(1:6)
output = vector("list", length = 6)




for (i in 1:6) {
  output[[i]] =  rerun(100, sim_norm(mu = mu_c[i])) %>%
  bind_rows()}

```

```{r}
output[[1+1]] = rerun(100, sim_norm(mu = mu_c[1])) %>%
  bind_rows()

```

```{r}

mu_c =c(1:7)
output = vector("list", length = 6)


for (i in 1:7) {
  output[[i]] =  rerun(100, sim_norm(mu = mu_c[i]-1)) %>%
  bind_rows()}

```




```{r}


sample_results = 
tibble(
  mu_c =c(1:7)
) %>%
  mutate(
    output_list = map(.x = mu_c-1,~rerun(5000,sim_norm(mu=.x))), #function inside of a function #rerun a 100 times
    estmate_df = map(output_list, bind_rows)
  )  %>%
  select(-output_list) %>% #i dont want this anymore 
  unnest(estmate_df) 

```

```{r}
sample_results%>%
  mutate(decision = ifelse(p.value<0.5,"reject","accept"),
         mu_c=mu_c-1)
```

```{r}
sample_results%>%
  mutate(decision = ifelse(p.value<0.05,"reject","accept"),
         mu_c=mu_c-1) %>%
  group_by(mu_c,decision) %>%
  filter(decision=="reject") %>%
  summarise(n_reject=n()) 

```




```{r}
sample_results%>%
  mutate(decision = ifelse(p.value<0.05,"reject","accept"),
          mu_c=mu_c-1)%>%
  group_by(decision,mu_c) %>%
  filter(decision=="reject") %>%
  summarise(n_reject=n()) %>%
   mutate(freq_reject= n_reject/1000)%>%
  ggplot(aes(x=mu_c, y=freq_reject,fill=mu_c)) + 
  geom_bar(stat = "identity") +
  scale_x_continuous(
    breaks = c(0:6)) +
  scale_y_continuous(
   n.breaks = 20) +
  labs(titles = "the proportion of time null-hypothesis is rejected",
        x = "true value of μ",
       y= " rejection with null mean=0") +
  theme(legend.position = "right")



  
```

 



